- name: disable nodejs
  ansible.builtin.command: dnf module disable nodejs -y

# dnf module enable nodejs:20 -y
- name: enable nodejs:20
  ansible.builtin.command: dnf module enable nodejs:20 -y

# dnf install nodejs -y
- name: install nodejs
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop:
  - nodejs
  - mysql

# useradd expense
- name: create expense user
  ansible.builtin.user:
    name: expense

# - name: create app directory
#   ansible.builtin.file:
#     path: /app
#     state: directory

# - name: download application code to app directory
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{component}}-v2.zip
#     dest: /tmp/backend.zip

# - name: unzip backend code
#   ansible.builtin.unarchive:
#     src: /tmp/backend.zip
#     dest: /app
#     remote_src: yes

- name: run app pre-requisites means common folder
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: install npm dependencies
  ansible.builtin.command: npm install
  args:
      chdir: /app

- name: copy backend service
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: systemctl daemon-reload
  ansible.builtin.service:
    daemon-reload: true

# - name: systemctl start and enabled service
#   ansible.builtin.service:
#     name: backend
#     state: started
#     enabled: yes

- name: installed mysql python dependencies
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9
          
# provided in loop
# - name: install mysql
#   ansible.builtin.dnf:
#     name: mysql
#     state: latest

- name: import data into mysql
  community.mysql.mysql_db:
    login_user: "{{login_user}}"
    login_password: "{{login_password}}"
    login_host: "{{login_host}}"
    target: /app/schema/backend.sql
    state: import
    name: all

# systemctl restart backend
- name: restart backend service
  ansible.builtin.service:
    name: backend
    state: restarted
    enabled: yes